### ISSUE TITLE
Can not remove php@7.2

### ISSUE THREAD

**Issue by GrantSmithDoddle** [shivammathur/homebrew-php#890] opened 2022-05-25 20:11 UTC
After running `brew uninstall shivammathur/php/php@7.2`, `brew list` still shows, `php@7.2`. `php@7.2` was installed via `brew install shivammathur/php/php@7.2`

**PHP versions**
php@7.2

**Expected behavior**
For `brew list` not to list `php@7.2`

**Comment by shivammathur** [comment] 2022-05-25 22:37
I could not reproduce the issue. It is removed from brew list after uninstall
https://github.com/shivammathur/test-setup-php/runs/6601202862?check_suite_focus=true

Please try running this
```zsh
brew update
brew cleanup
```

and then run `brew list`. 

If it is still there, please run `brew doctor` and fix any issues it reports.

After that run uninstall again, If php@7.2 is still there brew list, after you have uninstalled it, please provide me the logs of 
```zsh
brew uninstall shivammathur/php/php@7.2
```

**Comment by shivammathur** [comment] 2022-05-31 11:56
Closing the issue, please re-open if you are still facing this.

**Closed** 2022-05-31 11:56 UTC
Labels: support
