### ISSUE TITLE
can't install php7.4

### ISSUE THREAD

**Issue by longxianlin** [shivammathur/homebrew-php#2918] opened 2024-07-09 05:37 UTC
**Describe the bug**
brew install shivammathur/php/php@7.4

**PHP versions**
php7.4

**To Reproduce**

**Expected behavior**
install

**Screenshots/Logs**
<img width="920" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/7868765/2e9f266c-b549-4475-be17-ac015874e6e1">

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment] 2024-07-09 08:01
@longxianlin 
Please check your network connection, brew is not able to download the openssl formula which is a dependency of php.
This is not a bug in this tap, so closing.

**Closed by shivammathur** 2024-07-09 08:01 UTC
Labels: bug
